Repository arifulbgt4/MuiStory, pull requests merged in 2023-07, with the labels that each got.

#46 fix: sb docs overview change and override components
  docs/FormControl.stories.tsx
  docs/IconButton.stories.tsx
  docs/LoadingButton.stories.tsx
  docs/Menu.stories.tsx
  docs/Paper.stories.tsx
  docs/Tabs.stories.tsx
  src/theme/overrides/Button.ts
  src/theme/overrides/Checkbox.ts
  src/theme/overrides/FormControl.ts
  src/theme/overrides/List.tsx
  src/theme/overrides/Select.ts
  src/theme/overrides/Table.ts
  src/theme/overrides/TextField.ts
Labels: bug, documentation

#49 dependencies sb docs
  docs/Dependencies.mdx
Labels: documentation, missing

#54 Final form
  docs/Dependencies.mdx
  package.json
  src/app/lab/page.tsx
  src/components/Input/Checkbox.tsx
  src/components/Input/RadioGroup.tsx
  src/components/Input/Select.tsx
  src/components/Input/Slider.tsx
  src/components/Input/Switch.tsx
  src/components/Input/TextField.tsx
  src/components/Input/Types.ts
  src/components/Input/index.tsx
  src/components/Input/util.ts
  yarn.lock
Labels: documentation, enhancement, good first issue
